# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python package

on:
  push:
    # branches: [ $default-branch ]
    branches-ignore:
      - 'main'
      - 'develop'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        # os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        # python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install .[dev]
        python -m pip install .[test]
    - name: Test with tox
      run: |
        python -m tox -e py
        # echo "Passing :P"
    - name: Install deploy dependencies
      run: |
        python -m pip install -U setuptools wheel build
        if [ -f requirements-deploy.txt ]; then pip install -r requirements-deploy.txt; fi
        pip install .
    - name: Build package
      run: |
        changelog2version \
          --changelog_file changelog.md \
          --version_file src/be_modbus_wrapper/version.py \
          --version_file_type py \
          --debug
        python -m build .
    - name: Test built package
      run: |
        twine check dist/*.tar.gz
    - name: Archive build package artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.python-version == '3.9' }}
      with:
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # ${{ github.repository }} and ${{ github.ref_name }} can't be used for artifact name due to unallowed '/'
        name: dist_py.${{ matrix.python-version }}_repo.${{ github.event.repository.name }}_sha.${{ github.sha }}_build.${{ github.run_number }}
        path: dist/*.tar.gz
        retention-days: 14
